### ISSUE TITLE
ValueError: Namespace GtkSource not available

### ISSUE THREAD

**Issue by Innercode** [grovera-md/TechneNotes#1]
Hi,

Followed the instructions as stated in the README.

Installed the packages meson, python3-peewee, python3-markdown and python3-lxml
Cloned the repo
Chmodded install.sh to 755
Run the install.sh
Output:
```text
The Meson build system
Version: 0.61.2
Source dir: /mnt/hdd/live/Applications/TechneNotes
Build dir: /mnt/hdd/live/Applications/TechneNotes/builddir
Build type: native build
Project name: ovh.technenotes.myapp
Project version: undefined
Host machine cpu family: x86_64
Host machine cpu: x86_64
Configuring technenotes.desktop using configuration
Build targets in project: 0

Found ninja-1.10.1 at /usr/bin/ninja
Directory already configured.

Just run your build command (e.g. ninja) and Meson will regenerate as necessary.
If ninja fails, run "ninja reconfigure" or "meson --reconfigure"
to force Meson to regenerate.

If build failures persist, run "meson setup --wipe" to rebuild from scratch
using the same options as passed when configuring the build.
To change option values, run "meson configure" instead.
ninja: Entering directory `/mnt/hdd/live/Applications/TechneNotes/builddir'
ninja: no work to do.
Installation failed due to insufficient permissions.
Attempting to use polkit to gain elevated privileges...
ninja: Entering directory `/mnt/hdd/live/Applications/TechneNotes/builddir'
ninja: no work to do.
Installing /mnt/hdd/live/Applications/TechneNotes/data/ovh.technenotes.myapp.gschema.xml to /usr/local/share/glib-2.0/schemas
Installing /mnt/hdd/live/Applications/TechneNotes/data/markdown-extra-tech.lang to /usr/local/share/gtksourceview-3.0/language-specs
Installing /mnt/hdd/live/Applications/TechneNotes/data/codezone-tech.xml to /usr/local/share/gtksourceview-3.0/styles
Installing /mnt/hdd/live/Applications/TechneNotes/data/Lato-Regular.ttf to /usr/local/share/fonts
Installing /mnt/hdd/live/Applications/TechneNotes/builddir/technenotes.desktop to /usr/local/share/applications
Running custom install script '/usr/bin/glib-compile-schemas /usr/local/share/glib-2.0/schemas'
```

Than running src/technenotes.py gives the following error:
```text
Traceback (most recent call last):
  File "/mnt/hdd/live/Applications/TechneNotes/src/technenotes.py", line 4, in <module>
    gi.require_version('GtkSource', '3.0')
  File "/usr/lib/python3/dist-packages/gi/__init__.py", line 126, in require_version
    raise ValueError('Namespace %s not available' % namespace)
ValueError: Namespace GtkSource not available
```

Google-ing this error suggests that installing the following packages will help. python3-gi, gobject-introspection and gir1.2-gtk-3.0 It doesn't

Thanks in advance

**Comment by Innercode** [comment]
Fixed it! TechneNotes depends also on the packages gir1.2-gtksource-3.0 and gir1.2-webkit2-4.0

**Comment by grovera-md** [comment]
> Fixed it! TechneNotes depends also on the packages gir1.2-gtksource-3.0 and gir1.2-webkit2-4.0

Thank you very much @Innercode for raising this issue and contributing to its solution.
I am currently doing research on debian packaging. It would be nice to release the software through the official repositories, and the installation process would also be a lot easier. Your contribution will definitely be helpful in setting up all the dependencies for debian packaging.
By the way, if you are interested in this topic (linux packaging), you are welcome to contribute
